const departmentsData = [
  {
    name: 'Radiology & Imaging',
    code: 'RAD',
    headName: 'Dr. Robert Vance',
    location: 'Building A, Floor 1',
    description: 'Advanced diagnostic radiology, MRI, CT, and Ultrasound imaging suite.',
  },
  {
    name: 'Cardiology',
    code: 'CARD',
    headName: 'Dr. Elena Rostova',
    location: 'Building B, Floor 2',
    description: 'Comprehensive cardiac care, ECG, Defibrillators, and Angiography suite.',
  },
  {
    name: 'Intensive Care Unit (ICU)',
    code: 'ICU',
    headName: 'Dr. Marcus Sterling',
    location: 'Critical Care Tower, Floor 3',
    description: 'High-acuity patient care, mechanical ventilation, and vital sign monitoring.',
  },
  {
    name: 'General & Robotic Surgery',
    code: 'SURG',
    headName: 'Dr. Sarah Jenkins',
    location: 'Operation Theater Complex, Floor 4',
    description: 'Surgical theaters, anesthesia workstations, and electrosurgical units.',
  },
  {
    name: 'Emergency & Trauma',
    code: 'EMERG',
    headName: 'Dr. Alexander Hayes',
    location: 'Ground Floor, Emergency Wing',
    description: '24/7 Trauma response, portable X-ray, resuscitation, and rapid triage equipment.',
  },
];

const usersData = [
  {
    fullName: 'System Administrator',
    email: 'admin@medtrack.com',
    phone: '+1 (555) 019-2831',
    employeeId: 'EMP-ADM-001',
    department: 'Hospital Administration',
    designation: 'Chief Technology Officer',
    role: 'Admin',
    password: 'Admin@123',
    isActive: true,
  },
  {
    fullName: 'John Miller (Senior Bio-Med Tech)',
    email: 'tech.john@medtrack.com',
    phone: '+1 (555) 014-9922',
    employeeId: 'EMP-TCH-101',
    department: 'Radiology & Imaging',
    designation: 'Senior Biomedical Engineer',
    role: 'Technician',
    password: 'Tech@123',
    isActive: true,
  },
  {
    fullName: 'Sarah Connor (ICU Specialist Tech)',
    email: 'tech.sarah@medtrack.com',
    phone: '+1 (555) 017-8833',
    employeeId: 'EMP-TCH-102',
    department: 'Intensive Care Unit (ICU)',
    designation: 'Biomedical Equipment Specialist',
    role: 'Technician',
    password: 'Tech@123',
    isActive: true,
  },
  {
    fullName: 'Emily Davis (ICU Lead Nurse)',
    email: 'staff.emily@medtrack.com',
    phone: '+1 (555) 012-4411',
    employeeId: 'EMP-STF-201',
    department: 'Intensive Care Unit (ICU)',
    designation: 'Charge Nurse',
    role: 'Staff',
    password: 'Staff@123',
    isActive: true,
  },
  {
    fullName: 'Michael Chang (Cardiology Supervisor)',
    email: 'staff.michael@medtrack.com',
    phone: '+1 (555) 018-7755',
    employeeId: 'EMP-STF-202',
    department: 'Cardiology',
    designation: 'Clinical Operations Manager',
    role: 'Staff',
    password: 'Staff@123',
    isActive: true,
  },
];

const equipmentData = [
  {
    assetId: 'EQ-RAD-3001',
    equipmentName: 'Siemens Magnetom 3T MRI Scanner',
    category: 'Radiology & Imaging',
    department: 'Radiology & Imaging',
    manufacturer: 'Siemens Healthineers',
    model: 'Magnetom Vida 3T',
    serialNumber: 'SN-MRI-998231',
    purchaseDate: new Date('2022-03-15'),
    installationDate: new Date('2022-04-01'),
    warrantyExpiry: new Date('2027-04-01'),
    vendorName: 'Siemens Global Healthcare Supply',
    purchaseCost: 1450000,
    serviceInterval: 90,
    lastMaintenance: new Date('2026-05-10'),
    nextMaintenance: new Date('2026-08-10'), // Healthy
    equipmentStatus: 'Healthy',
    location: 'Radiology Suite 101',
    remarks: 'High-field MRI scanner. Cryogen level optimal at 98%.',
  },
  {
    assetId: 'EQ-RAD-3002',
    equipmentName: 'GE Healthcare Revolution 128-Slice CT Scanner',
    category: 'Radiology & Imaging',
    department: 'Radiology & Imaging',
    manufacturer: 'GE Healthcare',
    model: 'Revolution CT 128',
    serialNumber: 'SN-CT-774129',
    purchaseDate: new Date('2021-08-20'),
    installationDate: new Date('2021-09-10'),
    warrantyExpiry: new Date('2026-08-20'), // Expiring soon
    vendorName: 'GE Medical Systems',
    purchaseCost: 980000,
    serviceInterval: 60,
    lastMaintenance: new Date('2026-05-30'),
    nextMaintenance: new Date('2026-08-03'), // Due in 4 days!
    equipmentStatus: 'Due Soon',
    location: 'CT Bay 2',
    remarks: 'X-Ray tube count at 450,000 exposures. Calibration pending.',
  },
  {
    assetId: 'EQ-ICU-4001',
    equipmentName: 'Dräger Evita V800 Intensive Care Ventilator',
    category: 'Life Support',
    department: 'Intensive Care Unit (ICU)',
    manufacturer: 'Dräger Medical',
    model: 'Evita V800',
    serialNumber: 'SN-VENT-441092',
    purchaseDate: new Date('2023-01-10'),
    installationDate: new Date('2023-01-15'),
    warrantyExpiry: new Date('2028-01-15'),
    vendorName: 'Dräger Americas',
    purchaseCost: 45000,
    serviceInterval: 30,
    lastMaintenance: new Date('2026-06-01'),
    nextMaintenance: new Date('2026-07-01'), // Overdue!
    equipmentStatus: 'Maintenance Overdue',
    location: 'ICU Bedside 04',
    remarks: 'O2 sensor membrane replacement required.',
  },
  {
    assetId: 'EQ-CARD-1001',
    equipmentName: 'Zoll R Series Automated Defibrillator & Pacemaker',
    category: 'Cardiology',
    department: 'Cardiology',
    manufacturer: 'Zoll Medical',
    model: 'R Series ALS',
    serialNumber: 'SN-DEF-110293',
    purchaseDate: new Date('2020-05-10'),
    installationDate: new Date('2020-05-12'),
    warrantyExpiry: new Date('2025-05-12'), // Expired
    vendorName: 'Zoll Cardiac Care',
    purchaseCost: 18500,
    serviceInterval: 30,
    lastMaintenance: new Date('2026-05-01'),
    nextMaintenance: new Date('2026-05-31'), // Over 30 days overdue -> Critical
    equipmentStatus: 'Critical',
    location: 'Cardiac Care Unit - Crash Cart 1',
    remarks: 'Battery hold test failed on last self-check. Requires new battery pack.',
  },
  {
    assetId: 'EQ-SURG-5001',
    equipmentName: 'Mindray BeneVision N22 Patient Monitor System',
    category: 'Patient Monitoring',
    department: 'General & Robotic Surgery',
    manufacturer: 'Mindray North America',
    model: 'BeneVision N22',
    serialNumber: 'SN-MON-883011',
    purchaseDate: new Date('2024-02-14'),
    installationDate: new Date('2024-02-20'),
    warrantyExpiry: new Date('2029-02-20'),
    vendorName: 'Mindray Medical Direct',
    purchaseCost: 32000,
    serviceInterval: 90,
    lastMaintenance: new Date('2026-06-15'),
    nextMaintenance: new Date('2026-09-15'),
    equipmentStatus: 'Healthy',
    location: 'OR Room 3',
    remarks: 'Multi-parameter telemetry module operational.',
  },
  {
    assetId: 'EQ-EMERG-2001',
    equipmentName: 'Philips CX50 Compact Portable Ultrasound System',
    category: 'Radiology & Imaging',
    department: 'Emergency & Trauma',
    manufacturer: 'Philips Healthcare',
    model: 'CX50 XMATRIX',
    serialNumber: 'SN-ULT-552910',
    purchaseDate: new Date('2023-11-05'),
    installationDate: new Date('2023-11-10'),
    warrantyExpiry: new Date('2026-11-10'),
    vendorName: 'Philips Medical Solutions',
    purchaseCost: 75000,
    serviceInterval: 60,
    lastMaintenance: new Date('2026-06-20'),
    nextMaintenance: new Date('2026-08-20'),
    equipmentStatus: 'Healthy',
    location: 'Trauma Bay 1',
    remarks: 'Phased array cardiac probe recalibrated.',
  },
];

const settingsData = [
  {
    key: 'hospitalName',
    value: 'St. Jude General Hospital & Bio-Medical Research Institute',
    description: 'Hospital facility name displayed across all system reports and headers',
  },
  {
    key: 'alertEmailNotifications',
    value: true,
    description: 'Send automated email notifications for critical equipment alerts',
  },
  {
    key: 'maintenanceWarningDaysThreshold',
    value: 7,
    description: 'Days before maintenance due date to flag equipment as Due Soon',
  },
  {
    key: 'warrantyWarningDaysThreshold',
    value: 30,
    description: 'Days before warranty expiration date to trigger Warranty Expiring alert',
  },
];

module.exports = {
  departmentsData,
  usersData,
  equipmentData,
  settingsData,
};
